import {Book} from '../shared/types'

export const books : Book[] = [
  {
    adult: false,
    id: 1,
    genre_ids: [ 28, 14 ],
    title: 'The Shadow of the Wind',
    original_language: 'en',
    original_title: 'The Shadow of the Wind',
    overview: 'In post-war Barcelona, a young boy finds a mysterious book that changes his life forever, uncovering dark secrets linked to a forgotten author.',
    popularity: 892.5,
    release_date: '2001-04-01',
    vote_average: 8.7,
    vote_count: 4500,
    translations: {},
    user_id: "1"
  },
  {
    adult: false,
    id: 2,
    genre_ids: [ 18, 27 ],
    title: 'The Haunting of Hill House',
    original_language: 'en',
    original_title: 'The Haunting of Hill House',
    overview: 'Four strangers spend time in a secluded mansion, where supernatural forces and psychological horror intertwine in chilling ways.',
    popularity: 773.1,
    release_date: '1959-10-01',
    vote_average: 8.1,
    vote_count: 3300,
    translations: {},
    user_id: "1"

  },
  {
    adult: false,
    id: 3,
    genre_ids: [ 14, 10751 ],
    title: 'Harry Potter and the Sorcerer\'s Stone',
    original_language: 'en',
    original_title: 'Harry Potter and the Sorcerer\'s Stone',
    overview: 'A young boy discovers he is a wizard and attends a magical school, uncovering mysteries and forging lifelong friendships.',
    popularity: 2305.4,
    release_date: '1997-06-26',
    vote_average: 9.0,
    vote_count: 12000,
    translations: {},
    user_id: "1"
  },
  {
    adult: false,
    id: 4,
    genre_ids: [ 878, 18 ],
    title: 'Dune',
    original_language: 'en',
    original_title: 'Dune',
    overview: 'In a far-future desert planet, a young noble becomes embroiled in political and spiritual battles to control a valuable resource.',
    popularity: 1893.6,
    release_date: '1965-08-01',
    vote_average: 8.8,
    vote_count: 7800,
    translations: {},
    user_id: "1"
  },
  {
    adult: false,
    id: 5,
    genre_ids: [ 18, 10749 ],
    title: 'Pride and Prejudice',
    original_language: 'en',
    original_title: 'Pride and Prejudice',
    overview: 'A spirited young woman deals with issues of love, class, and reputation in 19th century England.',
    popularity: 1322.7,
    release_date: '1813-01-28',
    vote_average: 8.6,
    vote_count: 9200,
    translations: {},
    user_id: "1"
  },
  {
    adult: false,
    id: 6,
    genre_ids: [ 28, 35 ],
    title: 'Good Omens',
    original_language: 'en',
    original_title: 'Good Omens',
    overview: 'An angel and a demon team up to prevent the apocalypse, challenging the fate of humanity.',
    popularity: 1500.4,
    release_date: '1990-05-01',
    vote_average: 8.3,
    vote_count: 5600,
    translations: {},
    user_id: "1"
  },
  {
    adult: false,
    id: 7,
    genre_ids: [ 878, 12 ],
    title: 'The Martian',
    original_language: 'en',
    original_title: 'The Martian',
    overview: 'An astronaut is stranded on Mars and must survive with limited resources until he can be rescued.',
    popularity: 1692.8,
    release_date: '2011-09-27',
    vote_average: 8.5,
    vote_count: 8300,
    translations: {},
    user_id: "1"
  },
  {
    adult: false,
    id: 8,
    genre_ids: [ 18, 878 ],
    title: '1984',
    original_language: 'en',
    original_title: '1984',
    overview: 'In a dystopian world where the government controls every aspect of life, a man begins to rebel against the system.',
    popularity: 2411.2,
    release_date: '1949-06-08',
    vote_average: 9.1,
    vote_count: 11300,
    translations: {},
    user_id: "1"
  },
  {
    adult: false,
    id: 9,
    genre_ids: [ 14, 10749 ],
    title: 'The Night Circus',
    original_language: 'en',
    original_title: 'The Night Circus',
    overview: 'Two rival magicians enter a mysterious, magical circus where they must outwit each other in a battle of skill and love.',
    popularity: 1098.4,
    release_date: '2011-09-13',
    vote_average: 8.4,
    vote_count: 6700,
    translations: {},
    user_id: "1"
  },
  {
    adult: false,
    id: 10,
    genre_ids: [ 27, 878 ],
    title: 'Frankenstein',
    original_language: 'en',
    original_title: 'Frankenstein',
    overview: 'A scientist creates life in a monstrous experiment, with disastrous consequences for himself and those around him.',
    popularity: 1520.6,
    release_date: '1818-01-01',
    vote_average: 8.2,
    vote_count: 4500,
    translations: {},
    user_id: "1"
  },
  {
    adult: false,
    id: 11,
    genre_ids: [ 28, 14 ],
    title: 'Percy Jackson & the Olympians: The Lightning Thief',
    original_language: 'en',
    original_title: 'Percy Jackson & the Olympians: The Lightning Thief',
    overview: 'A teenager discovers he is a demigod and embarks on a journey to retrieve a stolen lightning bolt.',
    popularity: 1852.9,
    release_date: '2005-06-28',
    vote_average: 8.1,
    vote_count: 5200,
    translations: {},
    user_id: "1"
  },
  {
    adult: false,
    id: 12,
    genre_ids: [ 14, 10749 ],
    title: 'Twilight',
    original_language: 'en',
    original_title: 'Twilight',
    overview: 'A teenage girl falls in love with a vampire, leading to a story of supernatural romance and danger.',
    popularity: 2430.2,
    release_date: '2005-10-05',
    vote_average: 7.5,
    vote_count: 6200,
    translations: {},
    user_id: "1"
  },
  {
    adult: false,
    id: 13,
    genre_ids: [ 18, 36 ],
    title: 'The Book Thief',
    original_language: 'en',
    original_title: 'The Book Thief',
    overview: 'During WWII, a young girl in Nazi Germany finds solace in stealing books and sharing them with others.',
    popularity: 1602.7,
    release_date: '2005-09-01',
    vote_average: 8.7,
    vote_count: 7500,
    translations: {},
    user_id: "1"
  },
  {
    adult: false,
    id: 14,
    genre_ids: [ 35, 14 ],
    title: 'Alice\'s Adventures in Wonderland',
    original_language: 'en',
    original_title: 'Alice\'s Adventures in Wonderland',
    overview: 'A young girl falls into a magical world of whimsical characters and unexpected adventures.',
    popularity: 1720.4,
    release_date: '1865-11-26',
    vote_average: 8.3,
    vote_count: 5600,
    translations: {},
    user_id: "1"
  },
  {
    adult: false,
    id: 15,
    genre_ids: [ 18, 10749 ],
    title: 'To Kill a Mockingbird',
    original_language: 'en',
    original_title: 'To Kill a Mockingbird',
    overview: 'A young girl observes her father’s struggle for justice and equality in the racially divided American South.',
    popularity: 2354.5,
    release_date: '1960-07-11',
    vote_average: 9.3,
    vote_count: 9900,
    translations: {},
    user_id: "1"
  },
  {
    adult: false,
    id: 16,
    genre_ids: [ 28, 878 ],
    title: 'Ender\'s Game',
    original_language: 'en',
    original_title: 'Ender\'s Game',
    overview: 'A young boy is recruited into a space academy where he must master complex tactics to prepare for an alien invasion.',
    popularity: 1930.2,
    release_date: '1985-01-15',
    vote_average: 8.0,
    vote_count: 6900,
    translations: {},
    user_id: "1"
  },
  {
    adult: false,
    id: 17,
    genre_ids: [ 28, 14 ],
    title: 'The Name of the Wind',
    original_language: 'en',
    original_title: 'The Name of the Wind',
    overview: 'A man recounts his adventures in a world of magic, mystery, and danger.',
    popularity: 2105.6,
    release_date: '2007-03-27',
    vote_average: 9.1,
    vote_count: 8400,
    translations: {},
    user_id: "1"
  },
  {
    adult: false,
    id: 18,
    genre_ids: [ 878, 12 ],
    title: 'Foundation',
    original_language: 'en',
    original_title: 'Foundation',
    overview: 'In a galaxy-spanning empire, a visionary scientist establishes a foundation to preserve knowledge and rebuild society.',
    popularity: 1483.7,
    release_date: '1951-05-01',
    vote_average: 8.6,
    vote_count: 7500,
    translations: {},
    user_id: "1"
  },
  {
    adult: false,
    id: 19,
    genre_ids: [ 14, 18 ],
    title: 'American Gods',
    original_language: 'en',
    original_title: 'American Gods',
    overview: 'A man embarks on a road trip with a mysterious stranger, discovering a hidden world of gods and mythologies.',
    popularity: 1748.2,
    release_date: '2001-06-19',
    vote_average: 8.4,
    vote_count: 5100,
    translations: {},
    user_id: "1"
  },
  {
    adult: false,
    id: 20,
    genre_ids: [ 878, 28 ],
    title: 'Snow Crash',
    original_language: 'en',
    original_title: 'Snow Crash',
    overview: 'A computer virus threatens a virtual world, and a hacker must stop it before it spreads to reality.',
    popularity: 1635.9,
    release_date: '1992-06-01',
    vote_average: 8.2,
    vote_count: 4300,
    translations: {},
    user_id: "1"
  }
]
